RecipeWeb/Models/ErrorViewModel.cs
namespace RecipeWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RecipeWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeWeb.Models;
using System.Diagnostics;
using RecipeBizObjects;

namespace RecipeWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<bizRecipe> lst = bizRecipe.GetAll();
            return View(lst);
        }
        public IActionResult API()
        {
            return View();
        }
        public IActionResult RecipeListJS()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecipeWeb/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using RecipeBizObjects;
using System.Data;

namespace RecipeWeb.Controllers
{
    public class RecipeController : Controller
    {
        public ActionResult Index()
        {
            List<bizRecipe> lst = bizRecipe.GetAll();
            return View(lst);
        }
        [EnableCors("Policy1")]
        public ActionResult APIRecipeList()
        {
            List<bizRecipe> lst = bizRecipe.GetAll();
            return Json(lst);
        }

        [EnableCors("Policy1")]
        public ActionResult APICuisineList()
        {
            List<bizCuisine> lst = bizCuisine.GetAll();
            return Json(lst);
        }
        public ActionResult Detail(string id)
        {
            bizRecipe r = bizRecipe.Get("Code", id);
            return View(r);
        }
        public ActionResult Recipe(string id)
        {
            bizRecipe r = bizRecipe.Get("Code", id);
            return View(r);
        }
        public ActionResult Edit(string id)
        {
            bizRecipe r;
            if (string.IsNullOrEmpty(id))
            {
                r = new();
            }
            else
            {
                r = bizRecipe.Get("Code", id);
            }

            return View(r);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(bizRecipe recipeobj)
        {
            try
            {
                recipeobj.Save();
                return RedirectToAction(nameof(Index));
            }
            catch (CPUFramework.CPUException ex)
            {
                ViewBag.ErrorMessage = ex.FriendlyMessage;
                return View(recipeobj);
            }
        }
        public ActionResult Delete(string id)
        {
            bizRecipe r = bizRecipe.Get("Code", id);

            return View(r);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(bizRecipe recipe)
        {
            try
            {
                recipe.Delete();
                return RedirectToAction(nameof(Index));
            }
            catch (CPUFramework.CPUException ex)
            {
                recipe = bizRecipe.Get(recipe.RecipeId);
                ViewBag.ErrorMessage = ex.FriendlyMessage;
                return View(recipe);
            }
        }
    }
}

RecipeWeb/Views/Home/API.cshtml
<div class="row">
    <ul>
        <li class="list-item"><a target="_blank" href="/Recipe/APICuisineList">Cuisines</a></li>
        <li class="list-item"><a target="_blank" href="/Recipe/APIRecipeList">Recipes</a></li>
    </ul>
</div>

RecipeWeb/Views/Home/Index.cshtml
@using RecipeBizObjects
@model List<bizRecipe>
@{
    
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" style="font-size:100px; font-weight: bold">Food Works</h1>
    <hr/>
    <p style="font-size:20px">
        Discover food and drinks on Food Works for every occasion and any meal of the day. Whether it's quick and easy dinner or appetizers for entertaining, there’s a variety of inspiration to choose from.
What delicious dishes will you find today? Visit the corners of some of the top culinary creators on Food Works, take a trip through collections of international cuisines that are taking kitchens by storm.
    </p>
   
     <p>
        @foreach (bizRecipe r in Model) 
        {
            <img src="images/@(r.Num).jpg" width="300" height="300" />
           
         }
     </p> 
</div>

RecipeWeb/Views/Home/RecipeListJS.cshtml
@*AS: Amazing job! 100% I think it would be better to refer to recipe by its full name instead of rec.
*@
<div class="row">
    <div class="col-md-12">
        <h2 class="text-primary">Recipes</h2>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <button class="btn btn-success" onclick="RefreshList()">Refresh List</button>
        <button class="btn btn-primary" onclick="ShowAll()">Show All</button>
        <button class="btn btn-danger" onclick="HideAll()">Hide All</button>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <table class="table" id="tblRec">
        </table>
    </div>
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <div class="row" id="dvPeek" onclick="ClearPeek()">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row" id="dvAddToMeal">
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    const tblRec = document.getElementById("tblRec");
    const dvPeek = document.getElementById("dvPeek");
    const dvAddToMeal = document.getElementById("dvAddToMeal");

    let recarray = [];

    $().ready(function () {
        RefreshList();
    }
    )

    function RefreshList() {
        fetch("/recipe/APIRecipeList")
            .then(resp => resp.json())
            .then(json_array => ShowRecipeList(json_array));
    }
    function ShowRecipeList(json_array) {
        recarray = json_array;
        tblRec.replaceChildren();
        json_array.forEach(r => CreateRecRow(r));
    }
        function CreateRecRow(rec) {
            //AS This line can be taken out.
        const r = `
            <tr>
            <td><a href='/Recipe/Detail/${rec.code}'> ${rec.code}</a></td>
            <td>${GetShowButton(rec, true)}</td>
            <td>${GetShowButton(rec, false)}</td>
            </tr>`
        $("#tblRec").append(r);

        }
        function CreateRecCard(rec, peek) {
            const dv = peek ? dvPeek : dvAddToMeal;
            let card = `
                   <div id="${peek ? " " : GetCardId(rec.code)}" class="col-md-4">
                    <div class="card">
                    ${peek ? "" : `<div class="card-header d-flex justify-content-end pe-1"><button onclick=HideCard('${rec.code}') class="btn btn-danger">X</button></div>`}
              <img class="card-img-top" src="/images/${rec.num}.jpg" alt="Card image">
              <div class="card-body">
                <h4 class="card-title">${rec.recipeName}</h4>
                <p class="card-text">${rec.firstName + " " + rec.lastName}</p>
                <a href="/Recipe/Detail/${rec.code}" class="btn btn-primary">See Recipe</a>
              </div>
              </div>
            </div>`
            if (peek) {
                dv.innerHTML = card;
            }
            else {
                if (document.getElementById(GetCardId(rec.code)) != null) {
                    HideCard(rec.code);
                }
                dv.innerHTML = card + dv.innerHTML;
            }
        }
        function GetShowButton(rec, peek) {
            return `<button onclick='ShowRec("${rec.code}", ${peek})' class='btn btn-primary bg-primary'>${peek ? "Peek" : "Add To Meal"}</button>`
        }
        function ShowRec(code, peek) {
            const rec = recarray.find(r => r.code == code);
            CreateRecCard(rec, peek);
            window.scroll(0, 0);
        }
        function HideCard(code) {
            const id = GetCardId(code);
            const card = document.getElementById(id);
            dvAddToMeal.removeChild(card);

        }
        function ShowAll() {
            recarray.forEach(r => ShowRec(r.code, false));
        }
        function HideAll() {
            console.log(recarray);
            recarray.forEach(r => HideCard(r.code));
        }
        function ClearPeek() {
            dvPeek.replaceChildren();
        }
        function GetCardId(code) {
            return "card-" + code;
        }
</script>

RecipeWeb/Views/Recipe/Delete.cshtml
@model RecipeBizObjects.bizRecipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete @Model.RecipeName</h1>


<h3>Are you sure you want to delete @Model.RecipeName?</h3>


<div>
    <hr />
    <form asp-action="Delete">
        @Html.HiddenFor(model => model.RecipeId)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecipeWeb/Views/Recipe/Detail.cshtml
@using RecipeBizObjects
@model RecipeBizObjects.bizRecipe

@{
    ViewBag.Title = "Recipes";
}
<hr />
<h1 display-4" style="font-size:75px; font-weight: bold" class="center">@Model.RecipeName</h1>
<hr />
<br />
<div class="row">
    <div class="col-sm-3">
        <img src="/images/@(Model.Num).jpg" style="width:300px" />
    </div>
    <div class="col-sm-9">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CuisineName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CuisineName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RecipeName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RecipeName)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Calories)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Calories)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StatusName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StatusName)
            </dd>
        </dl>
    </div>
    <br />
    <div class="row">
    </div>
    <br />
    <div class="col-md-12">
        <ul>
            @foreach (bizRecipeIngredient i in Model.IngredientsList(true))
            {
                <li>@i.IngredientName</li>
            }
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ol>
            @foreach (bizSteps s in Model.StepsList(true))
            {
                <li>@s.StepDesc</li>
            }
        </ol>
    </div>
</div>
<br />
<hr />
<div class="row">
    <div class="col-md-2">
        @Html.ActionLink("Edit", "Edit", new {  id = @Model.Code  } , new{Class = "btn btn-primary"} )
        @Html.ActionLink("Delete", "Delete", new {id = Model.Code}, new{Class = "btn btn-danger"} )
    </div>
     <div class="col-md-1.5">
         <br />
    <a asp-action="Index">Back to List</a>
    </div>
</div>
  

RecipeWeb/Views/Recipe/Edit.cshtml
@model RecipeBizObjects.bizRecipe

@{
    ViewData["Title"] = "Edit";
    SelectList lstuser = new SelectList(Model.UserList(), "CreatedByUserId", "UserName");
    SelectList lstcuisine = new SelectList(Model.CuisineList(), "CuisineId", "CuisineName");
    
}

<h1>Edit @Model.RecipeName</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      
            <input type="hidden" asp-for="RecipeId" />
            <input type="hidden" asp-for="Num" />
             <div class="form-group">
                <label asp-for="CreatedByUserId" class="control-label"></label>
                <select asp-for="CreatedByUserId" asp-items=lstuser class="form-control">
                    <option value="">Select a User</option>
                </select>
                <span asp-validation-for="CreatedByUserId" class="text-danger"></span>
            </div>
            <br />
           <div class="form-group">
                <label asp-for="CuisineId" class="control-label"></label>
                <select asp-for="CuisineId" asp-items=lstcuisine class="form-control">
                    <option value="">Select a Cuisine</option>
                </select>
                <span asp-validation-for="CuisineId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
        
            <div class="form-group">
                <label asp-for="DraftDate" class="control-label"></label>
                <input asp-for="DraftDate" class="form-control" />
                <span asp-validation-for="DraftDate" class="text-danger"></span>
            </div>
            <br />
               <div class="form-group">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="ArchivedDate" class="control-label"></label>
                <input asp-for="ArchivedDate" class="form-control" />
                <span asp-validation-for="ArchivedDate" class="text-danger"></span>
            </div>
            <br />
                 <div class="form-group">
                <label asp-for="StatusName" class="control-label"></label>
                @Html.DisplayFor(model => model.StatusName)
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

RecipeWeb/Views/Recipe/Index.cshtml
@using RecipeBizObjects
@model List<bizRecipe>

<div class="row">
    <div class="col-md-12 text-center">
        <h1>Recipe</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped border border-2 border-dark">
         <tr>
            <td></td>
            <td style="font-weight:bold; font-size:20px">Recipe</td>
            <td style="font-weight:bold; font-size:20px">Calories</td>
            <td style="font-weight:bold; font-size:20px">Created By</td>
        </tr>
            @foreach (bizRecipe r in Model)
            {
                    <tr>
                        <td><img src="/images/@(r.Num).jpg" style="width:100px"/></td>
                        <td style="font-size:20px">@Html.ActionLink(r.RecipeName, "Detail", new{id=@r.Code})</td>
                        <td>@r.Calories</td>
                        <td style="font-size:20px">@r.FirstName @r.LastName</td>
                    </tr>
            }
        </table>
    </div>
</div>

RecipeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" href="images//icon food works.jpg"/>
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Food Works - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/minty-bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipeWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="font-weight:bold" asp-area="" asp-controller="Home" asp-action="Index">Recipes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RecipeListJS">Recipe List JS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="API">API</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <hr/>
    <div class="container">
           @if (ViewBag.ErrorMessage != null && string.IsNullOrEmpty(ViewBag.ErrorMessage.ToString()) == false)
        {
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-danger">@ViewBag.ErrorMessage</h3>
                </div>
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Recipe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>